baseURL = "http://example.org/"
languageCode = "en-us"
title = "PointyFar"
theme = "pointyfolio"

##### Set to ../../ so you can run hugo server from exampleSite.
##### If copying this config file, either remove themesDir or change to suit.
themesDir = "../../"

# pygmentsUseClassic = false
# pygmentsUseClasses = true
pygmentsUseClassic = true
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

paginate = 4

sectionPagesMenu = "main"

# disqusShortname = "disqusShortname"

[[menu.main]]
    name = "Blog"
    title = "Blog Section"
    weight = 120
    identifier = "post"
    url = "/post/"

[[menu.main]]
    name = "Tags"
    title = "Tags List"
    weight = 130
    identifier = "tags"
    url = "/tags/"

[params]
  subtitle = "Adventures in Hugoland"
  copyright = "Copyright © 2018"
  author = "Pointy Far"
  
  heroImage = "stock/mushroom.jpg"
  errorImage = "stock/missing-mushroom.png"
  
  footerNotice = "Powered by Hugo. Themed by PointyFar"
  mainSections = ["post"]
  
  swapFontawesome = ""

[params.highlight]
  enableHighlight = true
  #highlightCSS = "<link href=\"/css/chroma.css\" rel=\"stylesheet\">"
  
  ### To use highlight.js instead: 
  ##### uncomment below and set 
  ##### pygmentsUseClassic = true 
  ##### pygmentsUseClasses = false
  
  highlightCSS = "<link rel=\"stylesheet\" href=\"//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/default.min.css\">"
  highlightJS = "<script src=\"//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js\"></script>"
  

[params.cdn]
  enableCDN = false 
  listCDN = [
    "<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">",
    "<link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">",
    "<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>",

    "<script src=\"https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js\"></script>"

  ]

[[params.legal]]
  legalurl = "#"
  legaltext = "Privacy Policy"

[[params.legal]]
  legalurl = "#"
  legaltext = "Terms of Use"
  
  
  
[[params.social]]
  url = "http://www.twitter.com"
  icon = "fab fa-twitter"

[[params.social]]
  url = "http://www.facebook.com"
  icon = "fab fa-facebook"

[[params.social]]
  url = "http://www.instagram.com"
  icon = "fab fa-instagram"

[[params.social]]
  url = "http://www.tumblr.com"
  icon = "fab fa-tumblr"

[[params.social]]
  url = "http://www.github.com"
  icon = "fab fa-github"

